include: protect 32bit gmond module developers against APR header bug
workaround a bug in the APR headers in 32bit Linux that rely in off64_t
being defined, which is only the case when _LARGEFILE64_SOURCE is defined,
failing otherwise with :

  /usr/include/apr-1.0/apr.h:273: error: expected '=', ',', ';'. 'asm' or '__attribute__' before 'apr_off_t'

merged from trunk by :

  svn merge -c1488 trunk

Reviewed-by: Brad Nicholes <BNICHOLES@novell.com>