libmetrics: openbsd: clean dead code and add missing header
fixes :

metrics.c: In function `machine_type_func':
metrics.c:220: warning: implicit declaration of function `strncpy'
metrics.c: In function `cpu_state':
metrics.c:282: warning: implicit declaration of function `bzero'
metrics.c: In function `checkvfsname':
metrics.c:801: warning: implicit declaration of function `strcmp'
metrics.c: In function `makevfslist':
metrics.c:831: warning: implicit declaration of function `strchr'
metrics.c: In function `makenetvfslist':
metrics.c:871: warning: implicit declaration of function `strlen'
metrics.c:883: warning: implicit declaration of function `strcpy'
metrics.c:848: warning: unused variable `ptr'
metrics.c: At top level:
metrics.c:75: warning: `use_vm_swap_info' defined but not used
metrics.c:76: warning: `mibswap' defined but not used
metrics.c:77: warning: `mibswap_size' defined but not used