gmetad-python: enable RRD_ROOTDIR from the RRD module
reported broken by Steven A. Duchene when using a standard gmetad 
configuration with :

Traceback (most recent call last):
   File "gmetad.py", line 43, in ?
     from gmetad_gmondReader import GmondReader
   File gmetad_gmondReader.py", line 40, in ?
     from gmetad_config import GmetadConfig, getConfig
   File "gmetad_config.py", line 46, in ?
     class GmetadConfig:
   File "gmetad_config.py", line 69, in GmetadConfig
     _cfgDefaults = {
NameError: name 'RRD_ROOTDIR' is not defined